import torch


def find_candidate_double_points(model, grid_resolution, epsilon, tau, device=None, dtype = torch.float64):
    """
    Finds candidate double point pairs for an immersion u: D^2 -> R^4.
    
    Args:
        model: A torch.nn.Module mapping (N, 2) to (N, 4).
        grid_resolution: Int. The N in an N x N grid to generate over [-1, 1]^2.
        epsilon: Float. The domain threshold to ignore local continuity (the diagonal).
        tau: Float. The target space threshold for the self-proximity map.
        device: torch.device (Optional). If None, tries to infer from the model.
        
    Returns:
        candidate_pairs: A torch.Tensor of shape (num_candidates, 2, 2).
                         candidate_pairs[i, 0] is p1, candidate_pairs[i, 1] is p2.
    """
    if isinstance(model, torch.nn.Module):
        model.eval()
        # Attempt to automatically detect device if not provided
        if device is None:
            try:
                device = next(model.parameters()).device
            except StopIteration:
                device = torch.device('cpu')
    else:
        if device is None:
            device = torch.device('cpu')

    with torch.no_grad():
        # 1. Generate the regular grid over [-1, 1] x [-1, 1]
        x = torch.linspace(-1, 1, grid_resolution, dtype=dtype, device=device)
        y = torch.linspace(-1, 1, grid_resolution, dtype=dtype, device=device)
        grid_x, grid_y = torch.meshgrid(x, y, indexing='ij')
        
        # Flatten to shape (N*N, 2)
        p_grid = torch.stack([grid_x.flatten(), grid_y.flatten()], dim=1)
        
        # 2. Mask out points outside the unit disk D^2
        mask_disk = (p_grid[:, 0]**2 + p_grid[:, 1]**2) <= 1.0
        p = p_grid[mask_disk]
        
        # 3. Evaluate the model to get points in R^4. Shape: (num_valid_points, 4)
        u = model(p)
        
        # 4. Compute pairwise Euclidean distances in the domain (D^2)
        dist_p = torch.cdist(p, p, p=2.0)
        
        # 5. Compute pairwise Euclidean distances in the target (R^4)
        dist_u = torch.cdist(u, u, p=2.0)
        
        # 6. Mask out the diagonal. Set target distance to infinity if 
        # the points are closer than epsilon in the domain.
        dist_u[dist_p <= epsilon] = float('inf')
        
        # 7. Compute the self-proximity map mu_epsilon
        mu_eps, min_indices = torch.min(dist_u, dim=1)
        
        # 8. Find all points where the self-proximity is less than tau
        candidate_mask = mu_eps < tau
        
        # 9. Extract the candidate pairs (p1, p2)
        p1_candidates = p[candidate_mask]
        p2_candidates = p[min_indices[candidate_mask]]
        
        # Stack into shape (num_candidates, 2, 2)
        candidate_pairs = torch.stack((p1_candidates, p2_candidates), dim=1)
        
        return candidate_pairs
    

def refine_double_points_newton(u_callable, candidates, tol=1e-10, max_iter=50, dedup_tol=1e-5, disc_tol=1e-8, epsilon=1e-5, dtype=torch.float64):
    """
    Applies the Newton-Raphson method to find exact double points from initial candidates.
    
    Args:
        u_callable: PyTorch model mapping (N, 2) to (N, 4) in float64.
        candidates: List of tuples (p_cand, q_cand) generated by the candidate finder.
        tol: Convergence tolerance for ||F(X)||.
        max_iter: Maximum number of Newton steps.
        dedup_tol: Spatial tolerance to consider two converged roots as identical.
        disc_tol: Tolerance for checking if the solution lies within the unit disc D^2.
        epsilon: Minimum required distance between p and q to be considered a valid double point.
        
    Returns:
        refined_solutions: List of tuples (p_exact, q_exact) of the unique converged solutions.
        jac_determinants: List of floats representing the determinant of the Jacobian at each solution.
        final_distances: List of floats representing the final R^4 distance ||u(p) - u(q)||.
    """
    # Wrapper function mapping R^4 -> R^4 to feed into PyTorch's jacobian engine
    def F(x):
        # x is a 1D tensor of shape (4,) containing [p1_x, p1_y, p2_x, p2_y]
        p1 = x[:2].unsqueeze(0) # Shape: (1, 2)
        p2 = x[2:].unsqueeze(0) # Shape: (1, 2)
        
        # Calculate u(p1) - u(p2) and flatten back to shape (4,)
        return (u_callable(p1) - u_callable(p2)).squeeze(0)

    refined_solutions = []
    jac_determinants = []
    final_distances = [] 

    for idx, (p_cand, q_cand) in enumerate(candidates):
        # Stack p and q into a single 4D state vector X
        x = torch.cat([p_cand, q_cand]).clone().detach().to(dtype=dtype)
        
        converged = False
        
        for step in range(max_iter):
            # 1. Evaluate the function F(X)
            f_val = F(x)
            
            # Check for convergence
            if torch.norm(f_val) < tol:
                converged = True
                break
                
            # 2. Compute the 4x4 Jacobian matrix evaluated at x
            J = torch.autograd.functional.jacobian(F, x)
            
            # 3. Solve the linear system J * delta_x = -F(X) for delta_x
            try:
                delta_x = torch.linalg.solve(J, -f_val)
            except RuntimeError:
                # Silently break out of singular Jacobians to avoid spamming the console
                break
                
            # 4. Update state vector
            x = x + delta_x
            
        # Final evaluation at the converged root
        final_f_val = F(x)
        final_J = torch.autograd.functional.jacobian(F, x)
        
        # Calculate the determinant of the 4x4 Jacobian
        det_J = torch.linalg.det(final_J).item()
        
        # The distance in R^4 is exactly the norm of F(X)
        dist_R4 = torch.norm(final_f_val).item()
        
        # Split the 4D state vector back into two 2D points
        p_exact = x[:2]
        q_exact = x[2:]
        
        if converged:
            # Keep only roots inside the disc with p and q sufficiently separated
            if (torch.norm(p_exact) <= 1.0 + disc_tol and 
                torch.norm(q_exact) <= 1.0 + disc_tol and 
                torch.norm(p_exact - q_exact) > epsilon):
                
                refined_solutions.append((p_exact.detach(), q_exact.detach()))
                jac_determinants.append(det_J)
                final_distances.append(dist_R4)
            else:
                # Converged, but outside the disc or p and q are too close; drop it.
                pass

    # --- Filter out duplicate converged roots ---
    unique_solutions = []
    unique_jacs = []
    unique_dists = []
    
    for i, (p, q) in enumerate(refined_solutions):
        is_duplicate = False
        for (up, uq) in unique_solutions:
            # Check if it matches an existing root directly OR symmetrically
            if (torch.norm(p - up) < dedup_tol and torch.norm(q - uq) < dedup_tol) or \
               (torch.norm(p - uq) < dedup_tol and torch.norm(q - up) < dedup_tol):
                is_duplicate = True
                break
                
        if not is_duplicate:
            unique_solutions.append((p, q))
            unique_jacs.append(jac_determinants[i])
            unique_dists.append(final_distances[i])

    return unique_solutions, unique_jacs, unique_dists